In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix , accuracy_score , classification_report

In [3]:
url = r"C:\Users\vedba\Documents\DSBDAL_prac\iris.csv"
df = pd.read_csv(url)
df.head(10)

,sepal.length,sepal.width,petal.length,petal.width,variety
0,5.1,3.5,1.4,0.2,Setosa
1,4.9,3.0,1.4,0.2,Setosa
2,4.7,3.2,1.3,0.2,Setosa
3,4.6,3.1,1.5,0.2,Setosa
4,5.0,3.6,1.4,0.2,Setosa
5,5.4,3.9,1.7,0.4,Setosa
6,4.6,3.4,1.4,0.3,Setosa
7,5.0,3.4,1.5,0.2,Setosa
8,4.4,2.9,1.4,0.2,Setosa
9,4.9,3.1,1.5,0.1,Setosa


In [6]:
x=df.drop(['variety'], axis=1)
y=df['variety']

x_train,x_test,y_train,y_test = train_test_split(
    x,y,test_size=0.2,random_state=42
)

In [10]:
nb_model = GaussianNB()
nb_model.fit(x_train,y_train)

y_pred = nb_model.predict(x_test)
print(y_pred[:10])

['Versicolor' 'Setosa' 'Virginica' 'Versicolor' 'Versicolor' 'Setosa'
 'Versicolor' 'Virginica' 'Versicolor' 'Versicolor']


In [12]:
cm = confusion_matrix(y_test,y_pred)
print(cm)

[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


In [13]:
# 2. Extract TP, FP, FN, TN using matrix operations
# True Positives: The diagonal elements
TP = np.diag(cm)

# False Positives: Column sum minus the diagonal (TP)
FP = np.sum(cm, axis=0) - TP

# False Negatives: Row sum minus the diagonal (TP)
FN = np.sum(cm, axis=1) - TP

# True Negatives: Total matrix sum minus (TP + FP + FN)
TN = np.sum(cm) - (FP + FN + TP)

# 3. Apply the Mathematical Formulas
# Overall Accuracy: Total correct predictions over total overall predictions
total_predictions = np.sum(cm)
overall_accuracy = np.sum(TP) / total_predictions
overall_error_rate = 1 - overall_accuracy

# Precision and Recall per class 
# (Adding a tiny value 1e-6 to avoid Division by Zero if a class has 0 predictions)
precision = TP / (TP + FP + 1e-6)
recall = TP / (TP + FN + 1e-6)

# 4. Print the final computed values
print("=== Overall Metrics ===")
print(f"Overall Accuracy: {overall_accuracy * 100:.2f}%")
print(f"Overall Error Rate: {overall_error_rate * 100:.2f}%\n")

print("=== Class-Wise Metrics (Setosa, Versicolor, Virginica) ===")
print(f"True Positives (TP): {TP}")
print(f"False Positives (FP): {FP}")
print(f"False Negatives (FN): {FN}")
print(f"True Negatives (TN): {TN}\n")

# Formatting precision and recall arrays for clean printing
precision_pct = [f"{val * 100:.2f}%" for val in precision]
recall_pct = [f"{val * 100:.2f}%" for val in recall]

print(f"Precision per class: {precision_pct}")
print(f"Recall per class:    {recall_pct}")

=== Overall Metrics ===
Overall Accuracy: 100.00%
Overall Error Rate: 0.00%

=== Class-Wise Metrics (Setosa, Versicolor, Virginica) ===
True Positives (TP): [10  9 11]
False Positives (FP): [0 0 0]
False Negatives (FN): [0 0 0]
True Negatives (TN): [20 21 19]

Precision per class: ['100.00%', '100.00%', '100.00%']
Recall per class:    ['100.00%', '100.00%', '100.00%']
